/** Figma-exported assets (public/figma). */
export const figmaAssets = {
  home: "/figma/home.svg",
  stemPageBack: "/figma/stem-page-back.svg",
  settings: "/figma/settings.svg",
  fullscreen: "/figma/fullscreen.svg",
  backButton: "/figma/back-button.svg",
  menuButton: "/figma/menu-button.svg",
  send: "/figma/send.svg",
  fullscreenPlay: "/figma/fullscreen-play.svg",
  vocalIcon: "/figma/vocal-icon.svg",
  otherIcon: "/figma/other-icon.svg",
  bassIcon: "/figma/bass-icon.svg",
  drumsIcon: "/figma/drums-icon.svg",
  nowPlaying: "/figma/now-playing.svg",
  play: "/figma/play.svg",
  pause: "/figma/pause.svg",
  previousSong: "/figma/previous-song.svg",
  nextSong: "/figma/next-song.svg",
  progressBar: "/figma/progress-bar.svg",
  volume: "/figma/volume.svg",

  dropDown: "/figma/drop-down.svg",
  meterText: "/figma/meter-text.svg",
  stemTrack: "/figma/stem-track.png",
  stemTrackVocals: "/figma/stem-track-vocals.svg",
  stemTrackOther: "/figma/stem-track-other.svg",
  stemTrackDrums: "/figma/stem-track-drums.svg",
  stemTrackBass: "/figma/stem-track-bass.svg",
  soloIconDefault: "/figma/solo-icon-default.svg",
  soloIconClicked: "/figma/solo-icon-clicked.svg",
  muteIconDefault: "/figma/mute-icon-default.svg",
  muteIconClicked: "/figma/mute-icon-clicked.svg",
  background: "/figma/background.svg",
  /** Small star accents — layered over background.svg (1836×984 artboard) */
  smallStars: "/figma/small-stars.svg",
  letterbox: "/figma/letterbox.png",
  /** Legacy aliases */
  iconCircle: "/figma/icon-circle.svg",
} as const;
