import StarField from "../StarField";
import { useViewportSize } from "../../hooks/useViewportSize";
import { FIGMA } from "../../figma/layout";

const { width: FRAME_W } = FIGMA.frame;

/**
 * Small-stars overlay inside the 1920px player shell — now generated by the
 * shared jittered StarField (replaces the static small-stars.svg).
 * z-0 keeps it above the fixed gradient + decor (shell is its own context) but
 * under the main UI content (z-[1]).
 */
export default function PlayerBackground() {
  const { width, height } = useViewportSize();

  return (
    <div className="pointer-events-none absolute inset-0 z-0" aria-hidden>
      <StarField width={Math.min(width, FRAME_W)} height={height} />
    </div>
  );
}
